version: "3.8"
   
services:
  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=geekz
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:  # <-- connect to the bridge
      - database1_network
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn Geekz_Microschool.wsgi --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:  # <-- here
    - nginx_network
    - database1_network  # <-- connect to the bridge
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static
    networks:  # <-- here
    - nginx_network

volumes:
  postgres_data:
  static_volume:

networks:  # <-- and here
  nginx_network:
    driver: bridge
  database1_network:  # <-- add the bridge
    driver: bridge
