# Generated by Django 3.1.1 on 2020-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', 'QUEST_AUDN'),
    ]

    operations = [
        migrations.CreateModel(
            name='MICRO_APPLY',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IS_COMPLETE', models.CharField(default='N', max_length=1)),
                ('NAME', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('EMAIL', models.EmailField(max_length=254)),
                ('COUNTRY_CODE', models.IntegerField()),
                ('PHONE', models.BigIntegerField()),
                ('LOVE_TO_BE', models.CharField(max_length=15)),
                ('SCHOOL_MODE', models.CharField(max_length=25)),
                ('SCHOOL_OPERATE', models.CharField(max_length=25)),
                ('SCHOOL_LOCALITY', models.CharField(max_length=500)),
                ('LATITUDE', models.FloatField()),
                ('LONGITUDE', models.FloatField()),
                ('BUSINESS', models.CharField(max_length=50)),
                ('SCHOOL_NAME', models.CharField(blank=True, max_length=200, null=True)),
                ('SCHOOL_WEBSITE', models.CharField(blank=True, max_length=300, null=True)),
                ('SCHOOL_FB', models.URLField(blank=True, max_length=300, null=True)),
                ('LINKEDIN', models.URLField(max_length=300)),
                ('OCCUPATION', models.CharField(max_length=100)),
                ('PASSION', models.CharField(max_length=10000)),
                ('WHY_AFFILIATE', models.CharField(max_length=10000)),
            ],
        ),
    ]
