# Generated by Django 3.1.1 on 2020-11-23 13:11

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0001_micro_apply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='micro_apply',
            name='LATITUDE',
        ),
        migrations.RemoveField(
            model_name='micro_apply',
            name='LONGITUDE',
        ),
        migrations.AddField(
            model_name='micro_apply',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), geography=True, srid=4326),
        ),
    ]
