# Generated by Django 3.0.8 on 2020-12-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'USER_DETAILS'),
        ('schoolasaservice', '0002_auto_20201123_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='SLOTS_DAY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(max_length=200)),
                ('slot', models.TextField()),
                ('day', models.TextField()),
                ('duration', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EVENTS_SCHEDULE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summery', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('schedule_date', models.DateField()),
                ('dummy_field', models.CharField(max_length=200)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.SLOTS_DAY')),
                ('user_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.USER_DETAILS')),
            ],
            options={
                'unique_together': {('user_details', 'slot', 'start_time')},
            },
        ),
    ]
