# Generated by Django 3.0.8 on 2021-01-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0004_webdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='webdata21',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250, unique=True)),
                ('title', models.CharField(max_length=250, unique=True)),
                ('Infrastructure_affliation', models.CharField(max_length=250)),
                ('Education_affliation', models.CharField(max_length=250)),
                ('HomeSchool_affliation', models.CharField(max_length=250)),
                ('School_Fee_rule', models.CharField(max_length=250)),
                ('brandFee_rule', models.CharField(max_length=250)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('admin_email', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='webdata2',
        ),
    ]
