# Generated by Django 3.0.8 on 2021-01-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0005_auto_20210104_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='MICRO_PROFILING',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IS_PROFILINGCOMPLETE', models.CharField(default='N', max_length=1)),
                ('USER', models.CharField(max_length=250)),
                ('EVENT_ID', models.CharField(max_length=600)),
                ('ICalUID', models.CharField(max_length=600)),
                ('hangoutLink', models.CharField(max_length=600)),
                ('START_TIME', models.CharField(max_length=250)),
                ('END_TIME', models.CharField(max_length=250)),
                ('HEADING', models.CharField(max_length=300)),
            ],
        ),
    ]
