# Generated by Django 3.0.8 on 2021-01-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0006_micro_profiling'),
    ]

    operations = [
        migrations.CreateModel(
            name='RESCHEDULE_REASON',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=10000)),
            ],
        ),
    ]
