# Generated by Django 3.0.8 on 2021-01-08 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0007_reschedule_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='MICRO_PROFILIN',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IS_PROFILINGCOMPLETE', models.CharField(default='N', max_length=1)),
                ('schedule_date', models.DateField()),
                ('USER', models.CharField(max_length=250)),
                ('EVENT_ID', models.CharField(max_length=600)),
                ('ICalUID', models.CharField(max_length=600)),
                ('hangoutLink', models.CharField(max_length=600)),
                ('START_TIME', models.CharField(max_length=250)),
                ('END_TIME', models.CharField(max_length=250)),
                ('HEADING', models.CharField(max_length=300)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.SLOTS_DAY')),
            ],
        ),
        migrations.DeleteModel(
            name='MICRO_PROFILING',
        ),
    ]
