# Generated by Django 3.0.8 on 2021-01-25 14:38

from django.db import migrations, models
import schoolasaservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0013_auto_20210122_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=schoolasaservice.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='individual_webpagess',
            name='BANNER1',
            field=models.ImageField(blank=True, null=True, upload_to=schoolasaservice.models.content_file_name),
        ),
    ]
