# Generated by Django 3.0.8 on 2021-01-25 15:03

from django.db import migrations, models
import schoolasaservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0014_auto_20210125_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=400)),
                ('upload', models.FileField(upload_to=schoolasaservice.models.user_directory_path)),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
