# Generated by Django 3.0.8 on 2021-02-01 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0016_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 1, 10, 12, 26, 474000))),
                ('studentName', models.CharField(max_length=250)),
                ('enrolling_grade', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('message', models.CharField(max_length=700)),
                ('hear_about_us', models.CharField(max_length=250)),
                ('microschool', models.CharField(max_length=250)),
            ],
        ),
    ]
