# Generated by Django 3.0.8 on 2021-02-05 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0018_auto_20210201_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='media/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 5, 19, 29, 51, 876818)),
        ),
    ]
