# Generated by Django 3.0.8 on 2021-02-06 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0019_auto_20210205_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 6, 21, 9, 34, 336107)),
        ),
    ]
