# Generated by Django 3.0.8 on 2021-02-09 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0020_auto_20210206_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 9, 8, 54, 32, 605380)),
        ),
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to='gala/'),
        ),
    ]
