# Generated by Django 3.0.8 on 2021-02-09 03:45

import datetime
from django.db import migrations, models
import schoolasaservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0021_auto_20210209_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='INDIVIDUAL_WEBPAGESS1',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('SCHOOL_NAME', models.CharField(max_length=250)),
                ('LOCALITY', models.CharField(max_length=250)),
                ('AMENITIES_is_Spacious_Studio', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_Outdoor_PlayLawn', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_Commute', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_WiFi', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_CCTV', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_Device', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_Food', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_Daycare', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_After_School', models.CharField(default='N', max_length=1)),
                ('AMENITIES_is_Residential', models.CharField(default='N', max_length=1)),
                ('BANNER1', models.ImageField(blank=True, null=True, upload_to=schoolasaservice.models.user_directory_path)),
                ('BANNER2', models.ImageField(blank=True, null=True, upload_to=schoolasaservice.models.user_directory_path)),
                ('BANNER3', models.ImageField(blank=True, null=True, upload_to=schoolasaservice.models.user_directory_path)),
                ('BANNER4', models.ImageField(blank=True, null=True, upload_to=schoolasaservice.models.user_directory_path)),
                ('GOOGLE_REVIEWS_LINK', models.URLField(max_length=300)),
                ('FOUNDER_NAME', models.CharField(max_length=250)),
                ('DESIGNATION', models.CharField(max_length=250)),
                ('CO_FOUNDER1', models.CharField(max_length=250)),
                ('DESIGNATION_CO1', models.CharField(max_length=250)),
                ('CO_FOUNDER2', models.CharField(max_length=250)),
                ('DESIGNATION_CO2', models.CharField(max_length=250)),
                ('CONTENT1', models.CharField(max_length=1000)),
                ('CONTENT2', models.CharField(max_length=1000)),
                ('CONTENT3', models.CharField(max_length=1000)),
                ('ADDRESS1', models.CharField(max_length=400)),
                ('ADDRESS2', models.CharField(max_length=400)),
                ('SCHOOL_LOCALITY', models.CharField(max_length=400)),
                ('SCHOOL_PHONE', models.BigIntegerField()),
                ('SCHOOL_PHONE1', models.BigIntegerField()),
                ('SCHOOL_EMAIL', models.EmailField(max_length=254)),
                ('SCHOOL_HOURS_KS', models.CharField(max_length=250)),
                ('SCHOOL_HOURS_ES', models.CharField(max_length=250)),
                ('IS_COMPLETE', models.CharField(default='N', max_length=1)),
                ('IS_APPROVED', models.CharField(default='N', max_length=1)),
                ('LATITUDE', models.FloatField(max_length=600)),
                ('LONGITUDE', models.FloatField(max_length=600)),
            ],
        ),
        migrations.DeleteModel(
            name='INDIVIDUAL_WEBPAGESS',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 9, 9, 15, 57, 285608)),
        ),
    ]
