# Generated by Django 3.0.8 on 2021-02-09 04:59

import datetime
from django.db import migrations, models
import django.db.models.deletion
import schoolasaservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0022_auto_20210209_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=schoolasaservice.models.user_directory_path_gala)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gala_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.INDIVIDUAL_WEBPAGESS1')),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 9, 10, 29, 47, 138247)),
        ),
    ]
