# Generated by Django 3.0.8 on 2021-02-16 13:58

import datetime
from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0024_auto_20210216_1916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel1',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 19, 28, 0, 999073)),
        ),
        migrations.AlterField(
            model_name='photo_webpage1',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='photos'),
        ),
    ]
