# Generated by Django 3.0.8 on 2021-02-17 07:00

import datetime
from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0027_auto_20210217_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 12, 30, 10, 185796)),
        ),
        migrations.AlterField(
            model_name='photo_webpage1',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='photos'),
        ),
    ]
