# Generated by Django 3.0.8 on 2021-02-19 05:52

import datetime
from django.db import migrations, models
import django_imgur.storage
import schoolasaservice.models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0029_auto_20210219_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 19, 11, 22, 12, 842060)),
        ),
        migrations.AlterField(
            model_name='photo_webpage1',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to=schoolasaservice.models.user_directory_path_gala),
        ),
    ]
