# Generated by Django 3.0.8 on 2021-02-19 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0030_auto_20210219_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 19, 13, 39, 39, 549318)),
        ),
    ]
