# Generated by Django 3.0.8 on 2021-02-19 08:32

import datetime
from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0031_auto_20210219_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 19, 14, 1, 16, 650938)),
        ),
        migrations.AlterField(
            model_name='photo_webpage1',
            name='file',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='geekz'),
        ),
    ]
