# Generated by Django 3.0.8 on 2021-02-22 07:58

import datetime
from django.db import migrations, models
import django_imgur.storage


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0032_auto_20210219_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual_webpagess1',
            name='BANNER1',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='geekz'),
        ),
        migrations.AlterField(
            model_name='individual_webpagess1',
            name='BANNER2',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='geekz'),
        ),
        migrations.AlterField(
            model_name='individual_webpagess1',
            name='BANNER3',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='geekz'),
        ),
        migrations.AlterField(
            model_name='individual_webpagess1',
            name='BANNER4',
            field=models.ImageField(blank=True, null=True, storage=django_imgur.storage.ImgurStorage(), upload_to='geekz'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 22, 13, 27, 36, 572668)),
        ),
    ]
