# Generated by Django 3.0.8 on 2021-02-23 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0033_auto_20210222_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='notify_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=300)),
                ('phone', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 23, 19, 16, 54, 182652)),
        ),
    ]
