# Generated by Django 3.0.8 on 2021-02-24 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0034_auto_20210223_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('feedback', models.CharField(max_length=700)),
                ('rating', models.CharField(max_length=1)),
                ('user_id', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='feedback',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 24, 10, 55, 7, 75004)),
        ),
    ]
