# Generated by Django 3.0.8 on 2021-02-25 05:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0036_auto_20210224_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('feedback', models.CharField(max_length=700)),
                ('rating', models.IntegerField()),
                ('user_id', models.CharField(max_length=100)),
                ('SCHOOL', models.CharField(max_length=100)),
                ('school_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.INDIVIDUAL_WEBPAGESS1')),
            ],
        ),
        migrations.DeleteModel(
            name='feedback_users',
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 25, 11, 3, 48, 893598)),
        ),
    ]
