# Generated by Django 3.0.8 on 2021-02-25 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0037_auto_20210225_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryS',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 25, 18, 35, 40, 378371))),
                ('studentName', models.CharField(max_length=250)),
                ('enrolling_grade', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('ISAPPROVED', models.CharField(default='N', max_length=1)),
                ('hear_about_us', models.CharField(max_length=250)),
                ('microschool', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
