# Generated by Django 3.0.8 on 2021-02-26 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0040_auto_20210226_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 26, 11, 51, 58, 147580)),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
