# Generated by Django 3.0.8 on 2021-02-26 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0041_auto_20210226_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('SaaSDOB', models.DateField()),
                ('enrolling_grade', models.CharField(max_length=250)),
                ('attendedschool', models.CharField(max_length=250)),
                ('Fathersname', models.CharField(max_length=250)),
                ('Fathersoccupation', models.CharField(max_length=250)),
                ('Mothersname', models.CharField(max_length=250)),
                ('Mothersoccupation', models.CharField(max_length=250)),
                ('income', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('geekzcommute', models.CharField(max_length=250)),
                ('yescommutelocation', models.CharField(max_length=250)),
                ('childproud', models.CharField(max_length=800)),
                ('familyactivities', models.CharField(max_length=800)),
                ('childsinterests', models.CharField(max_length=800)),
                ('yourdreams', models.CharField(max_length=800)),
                ('medicalcondition', models.CharField(max_length=800)),
                ('childsuspended', models.CharField(max_length=800)),
                ('anythingelse', models.CharField(max_length=800)),
                ('hear_about', models.CharField(max_length=100)),
                ('IS_COMPLETE', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='studentApplication',
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 26, 13, 11, 22, 820729)),
        ),
    ]
