# Generated by Django 3.0.8 on 2021-02-26 15:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0044_auto_20210226_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 26, 21, 19, 29, 439713)),
        ),
        migrations.CreateModel(
            name='Individual_admin_slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.TextField()),
                ('day', models.TextField()),
                ('duration', models.TextField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.INDIVIDUAL_WEBPAGESS1')),
            ],
        ),
    ]
