# Generated by Django 3.0.8 on 2021-02-27 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0047_auto_20210227_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('Fathersname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=250)),
                ('microschool', models.CharField(max_length=800)),
                ('student_id', models.CharField(max_length=100)),
                ('IS_COMPLETE', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 27, 18, 23, 22, 942076)),
        ),
        migrations.DeleteModel(
            name='InvoiceRequests',
        ),
    ]
