# Generated by Django 3.0.8 on 2021-03-01 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0048_auto_20210227_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='transcriptsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('Fathersname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=250)),
                ('microschool', models.CharField(max_length=800)),
                ('student_id', models.CharField(max_length=100)),
                ('payment_complete', models.CharField(default='N', max_length=1)),
                ('IS_COMPLETE', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 1, 13, 53, 47, 585503)),
        ),
    ]
