# Generated by Django 3.0.8 on 2021-03-01 11:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0049_auto_20210301_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentApplications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('SaaSDOB', models.DateField()),
                ('enrolling_year', models.CharField(max_length=250)),
                ('enrolling_grade', models.CharField(max_length=250)),
                ('attendedschool', models.CharField(max_length=250)),
                ('Fathersname', models.CharField(max_length=250)),
                ('Fathersoccupation', models.CharField(max_length=250)),
                ('Mothersname', models.CharField(max_length=250)),
                ('Mothersoccupation', models.CharField(max_length=250)),
                ('income', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.BigIntegerField()),
                ('geekzcommute', models.CharField(max_length=250)),
                ('yescommutelocation', models.CharField(max_length=250)),
                ('childproud', models.CharField(max_length=800)),
                ('familyactivities', models.CharField(max_length=800)),
                ('childsinterests', models.CharField(max_length=800)),
                ('yourdreams', models.CharField(max_length=800)),
                ('medicalcondition', models.CharField(max_length=800)),
                ('childsuspended', models.CharField(max_length=800)),
                ('anythingelse', models.CharField(max_length=800)),
                ('hear_about', models.CharField(max_length=100)),
                ('IS_COMPLETE', models.CharField(default='N', max_length=1)),
                ('status', models.CharField(max_length=250)),
                ('student_id', models.CharField(max_length=100)),
                ('microschool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.INDIVIDUAL_WEBPAGESS1')),
            ],
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 1, 17, 18, 15, 724861)),
        ),
        migrations.DeleteModel(
            name='studentApplication',
        ),
    ]
