# Generated by Django 3.0.8 on 2021-03-02 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0051_auto_20210301_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 2, 10, 58, 36, 776099)),
        ),
        migrations.CreateModel(
            name='enrolledStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.CharField(default='N', max_length=1)),
                ('fees_paid', models.CharField(default='N', max_length=1)),
                ('student_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.studentApplication')),
            ],
        ),
    ]
