# Generated by Django 3.0.8 on 2021-03-02 05:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0052_auto_20210302_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfilings',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IS_PROFILINGCOMPLETE', models.CharField(default='N', max_length=1)),
                ('IS_APPROVED', models.CharField(default='N', max_length=1)),
                ('schedule_date', models.DateField()),
                ('USER', models.CharField(max_length=250)),
                ('EVENT_ID', models.CharField(max_length=600)),
                ('ICalUID', models.CharField(max_length=600)),
                ('hangoutLink', models.CharField(max_length=600)),
                ('START_TIME', models.CharField(max_length=250)),
                ('END_TIME', models.CharField(max_length=250)),
                ('HEADING', models.CharField(max_length=300)),
                ('modeofprofiling', models.CharField(max_length=300)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.Individual_admin_slots')),
            ],
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 2, 11, 12, 20, 113295)),
        ),
        migrations.DeleteModel(
            name='StudentProfiling',
        ),
    ]
