# Generated by Django 3.0.8 on 2021-03-02 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0053_auto_20210302_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='id',
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 2, 11, 51, 5, 456323)),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='student_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
