# Generated by Django 3.0.8 on 2021-03-02 09:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0054_auto_20210302_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 2, 15, 16, 32, 759419)),
        ),
        migrations.CreateModel(
            name='individual_feedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annualFee', models.IntegerField()),
                ('fee_TERM1', models.IntegerField()),
                ('fee_TERM2', models.IntegerField()),
                ('fee_TERM3', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.INDIVIDUAL_WEBPAGESS1')),
            ],
        ),
    ]
