# Generated by Django 3.0.8 on 2021-03-04 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0058_auto_20210303_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='individual_feedetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullYear_kindergarten', models.IntegerField()),
                ('fall_kindergarten', models.IntegerField()),
                ('spring_kindergarten', models.IntegerField()),
                ('fullYear_lowerElementary', models.IntegerField()),
                ('fall_lowerElementary', models.IntegerField()),
                ('spring_lowerElementary', models.IntegerField()),
                ('fullYear_UpperElementary', models.IntegerField()),
                ('fall_UpperElementary', models.IntegerField()),
                ('spring_UpperElementary', models.IntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.INDIVIDUAL_WEBPAGESS1')),
            ],
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 4, 15, 45, 31, 191021)),
        ),
        migrations.DeleteModel(
            name='individual_feedetails',
        ),
    ]
