# Generated by Django 3.0.8 on 2021-03-05 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0060_auto_20210305_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 5, 19, 17, 47, 846164)),
        ),
        migrations.AlterUniqueTogether(
            name='individual_admin_slots',
            unique_together={('admin_id', 'slot', 'day')},
        ),
    ]
