# Generated by Django 3.0.8 on 2021-03-05 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0061_auto_20210305_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 5, 22, 43, 46, 428887)),
        ),
        migrations.AlterField(
            model_name='slots_day',
            name='day',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slots_day',
            name='duration',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='slots_day',
            name='slot',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='slots_day',
            unique_together={('admin', 'slot', 'day')},
        ),
    ]
