# Generated by Django 3.0.8 on 2021-03-06 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0062_auto_20210305_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 0, 13, 8, 324865)),
        ),
        migrations.CreateModel(
            name='AffliatesfeeStructure',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('TaxfullYear_kindergarten', models.IntegerField()),
                ('total_fullYear_kindergarten', models.IntegerField()),
                ('split1_fullYear_kindergarten', models.IntegerField()),
                ('split2_fullYear_kindergarten', models.IntegerField()),
                ('split3_fullYear_kindergarten', models.IntegerField()),
                ('Taxfall_kindergarten', models.IntegerField()),
                ('total_fall_kindergarten', models.IntegerField()),
                ('split1_fall_kindergarten', models.IntegerField()),
                ('split2_fall_kindergarten', models.IntegerField()),
                ('Taxspring_kindergarten', models.IntegerField()),
                ('total_spring_kindergarten', models.IntegerField()),
                ('split1_spring_kindergarten', models.IntegerField()),
                ('TaxfullYear_lowerElementary', models.IntegerField()),
                ('total_fullYear_lowerElementary', models.IntegerField()),
                ('split1_fullYear_lowerElementary', models.IntegerField()),
                ('split2_fullYear_lowerElementary', models.IntegerField()),
                ('split3_fullYear_lowerElementary', models.IntegerField()),
                ('Taxfall_lowerElementary', models.IntegerField()),
                ('total_fall_lowerElementary', models.IntegerField()),
                ('split1_fall_lowerElementary', models.IntegerField()),
                ('split2_fall_lowerElementary', models.IntegerField()),
                ('Taxspring_lowerElementary', models.IntegerField()),
                ('total_spring_lowerElementary', models.IntegerField()),
                ('split1_spring_lowerElementary', models.IntegerField()),
                ('TaxfullYear_UpperElementary', models.IntegerField()),
                ('total_fullYear_UpperElementary', models.IntegerField()),
                ('split1_fullYear_UpperElementary', models.IntegerField()),
                ('split2_fullYear_UpperElementary', models.IntegerField()),
                ('split3_fullYear_UpperElementary', models.IntegerField()),
                ('Taxfall_UpperElementary', models.IntegerField()),
                ('total_fall_UpperElementary', models.IntegerField()),
                ('split1_fall_UpperElementary', models.IntegerField()),
                ('split2_fall_UpperElementary', models.IntegerField()),
                ('Taxspring_UpperElementary', models.IntegerField()),
                ('total_spring_UpperElementary', models.IntegerField()),
                ('split1_spring_UpperElementary', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.individual_feedetail')),
            ],
        ),
    ]
