# Generated by Django 3.0.8 on 2021-03-06 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0063_auto_20210307_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_fall_UpperElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_fall_kindergarten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_fall_lowerElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_fullYear_UpperElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_fullYear_kindergarten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_fullYear_lowerElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_spring_UpperElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_spring_kindergarten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split1_spring_lowerElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split2_fall_UpperElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split2_fall_kindergarten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split2_fall_lowerElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split2_fullYear_UpperElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split2_fullYear_kindergarten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split2_fullYear_lowerElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split3_fullYear_UpperElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split3_fullYear_kindergarten',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='affliatesfeestructure',
            name='split3_fullYear_lowerElementary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 0, 34, 10, 308178)),
        ),
    ]
