# Generated by Django 3.0.8 on 2021-03-07 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0064_auto_20210307_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='affliatesfeestructure',
            name='IS_FEEREVIEW_COMPLETE',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 19, 32, 12, 727137)),
        ),
    ]
