# Generated by Django 3.0.8 on 2021-03-08 16:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0067_auto_20210308_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='enrolledStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_status', models.CharField(default='N', max_length=1)),
                ('Term1', models.CharField(max_length=300)),
                ('Term1flag', models.CharField(default='N', max_length=1)),
                ('Term2', models.CharField(max_length=300)),
                ('Term2flag', models.CharField(default='N', max_length=1)),
                ('Term3', models.CharField(max_length=300)),
                ('Term3flag', models.CharField(default='N', max_length=1)),
                ('academic_year', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.INDIVIDUAL_WEBPAGESS1')),
                ('student_enrolled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.studentApplications')),
            ],
            options={
                'unique_together': {('student_enrolled', 'academic_year')},
            },
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 8, 21, 56, 10, 302764)),
        ),
        migrations.DeleteModel(
            name='enrolledStudents',
        ),
    ]
