# Generated by Django 3.0.8 on 2021-03-11 08:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0071_auto_20210310_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoicecounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_value', models.BigIntegerField(default=107)),
            ],
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 11, 13, 47, 59, 642421)),
        ),
        migrations.CreateModel(
            name='studentInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.IntegerField()),
                ('edTech', models.IntegerField()),
                ('Totalfees', models.IntegerField()),
                ('amountpaid', models.IntegerField()),
                ('academic_year', models.CharField(max_length=300)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.enrolledStudents')),
            ],
        ),
    ]
