# Generated by Django 3.0.8 on 2021-03-11 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0072_auto_20210311_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 11, 15, 16, 12, 615561)),
        ),
    ]
