# Generated by Django 3.0.8 on 2021-03-11 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0073_auto_20210311_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='duedates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Term1_duedate', models.DateField()),
                ('Term2_duedate', models.DateField()),
                ('Term3_duedate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 11, 21, 59, 54, 690549)),
        ),
    ]
