# Generated by Django 3.0.8 on 2021-03-11 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0074_auto_20210311_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 11, 22, 35, 47, 161526)),
        ),
    ]
