# Generated by Django 3.0.8 on 2021-03-12 10:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0075_auto_20210311_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 15, 55, 18, 820189)),
        ),
        migrations.CreateModel(
            name='MicroProfile_feedback',
            fields=[
                ('Profiling_done', models.CharField(default='N', max_length=1)),
                ('feedback', models.CharField(max_length=900)),
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('micro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.MICRO_PROFILING')),
            ],
        ),
    ]
