# Generated by Django 3.0.8 on 2021-03-12 16:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', '0076_auto_20210312_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquirys',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 22, 24, 9, 574556)),
        ),
        migrations.CreateModel(
            name='studentProfileFeedback',
            fields=[
                ('Profiling_done', models.CharField(default='N', max_length=1)),
                ('feedback', models.CharField(max_length=900)),
                ('school', models.CharField(max_length=300)),
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('studentProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolasaservice.StudentProfilings')),
            ],
        ),
    ]
