# Generated by Django 3.1.1 on 2020-10-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolasaservice', 'MICRO_AUDN'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUEST_AUDN',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('IS_COMPLETE', models.CharField(default='N', max_length=1)),
                ('IS_APPROVED', models.CharField(default='N', max_length=1)),
                ('ENGLISH_FLUENCY', models.CharField(max_length=15)),
                ('CODING_SKILL', models.CharField(max_length=15)),
                ('PHOTO_EDITING', models.CharField(max_length=15)),
                ('VIDEO_EDITING', models.CharField(max_length=15)),
                ('PASSION_TO_LEARN', models.CharField(max_length=10)),
                ('HD_WEBCAM', models.CharField(max_length=5)),
                ('INTERNET_MODE', models.CharField(max_length=20)),
                ('INTERNET_SPEED', models.CharField(max_length=5)),
                ('YOUTUBE_VIDEO', models.URLField(max_length=300)),
                ('NO_OF_STUDENTS', models.IntegerField()),
                ('QUESTIONS', models.CharField(max_length=10000)),
            ],
        ),
    ]
