# Generated by Django 3.1.1 on 2020-10-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='USER_DETAILS',
            fields=[
                ('uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('FULL_NAME', models.CharField(max_length=100)),
                ('USER_EMAIL', models.EmailField(max_length=254, unique=True)),
                ('CONTACT_PHONE', models.BigIntegerField()),
                ('PHONE_CTRY_CODE', models.IntegerField()),
                ('WHATSAPP_FLAG', models.CharField(default='N', max_length=1)),
                ('AUTH_TYPE', models.IntegerField()),
                ('IS_PARENT', models.CharField(default='N', max_length=1)),
                ('IS_STUDENT', models.CharField(default='N', max_length=1)),
                ('IS_MICROSCHOOL', models.CharField(default='N', max_length=1)),
                ('IS_QUESTSCHOOL', models.CharField(default='N', max_length=1)),
                ('IS_HOMESCHOOL', models.CharField(default='N', max_length=1)),
                ('PHOTO_URL', models.URLField(max_length=300)),
            ],
        ),
    ]
